
// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But we want to create a custom sidebar for our book chapters
  bookSidebar: [
    {
      type: 'category',
      label: 'Aaliya Raheem Physical Humanize AI Robot',
      items: [
        'chapter1',
        'chapter2',
        'chapter3',
        'chapter4',
        'chapter5',
        'chapter6',
      ],
    },
  ],
};

module.exports = sidebars;
